# fly.toml app configuration file generated for motoguide-fact-proxy.
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'motoguide-fact-proxy'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'
  OPENAI_MODEL = 'gpt-4o-mini'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
